# Base image
FROM node:18-alpine

# Create app directory
WORKDIR /app
COPY package*.json yarn.lock /app/

# Install app dependencies
RUN yarn install
# Bundle app source
COPY . /app

RUN yarn run build
# Start the server using the production build
EXPOSE 3000
CMD [ "node", "dist/main.js" ]