services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - NODE_ENV=development
    container_name: backend
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres
    links:
      - postgres:postgres
    restart: on-failure:3

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres

volumes:
  redis:
    driver: local
