services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - NODE_ENV=development
    container_name: backend
    env_file:
      - .env.staging
    ports:
      - 8585:3000
    depends_on:
      - redis
      - postgres
    links:
      - postgres:postgres
    restart: on-failure:3
    command: sh -c "yarn migration:run && yarn db:seed && yarn start:prod"

  redis:
    image: redis
    container_name: redis
    ports:
      - 6380:6379
    volumes:
      - redis:/var/lib/redis

  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=digihome

volumes:
  redis:
    driver: local
