export enum EACTION {
  RETURN_PREVIOUS = "RETURN_PREVIOUS",
  SAVE_DESIGN = "SAVE_DESIGN",
  LOAD_DESIGN = "LOAD_DESIGN",
  INIT_FRAME = "INIT_FRAME",
}

export enum EACTION_TO_CLIENT {
  LOAD_DESIGN_CLIENT = "LOAD_DESIGN_CLIENT",
}
