AWSTemplateFormatVersion: "2010-09-09"
Description: "cloudfront and s3 for blu3d and digihome"

Resources:
  S3Bucket:
    DeletionPolicy: "Delete"
    Metadata:
      Comment: "Bucket to store some data"
    Properties:
      AccessControl: "Private"
      BucketName: !Sub "digihome-${AWS::StackName}-${AWS::AccountId}"
    Type: "AWS::S3::Bucket"

  S3BucketPolicy:
    Metadata:
      Comment: "Bucket policy to allow cloudfront to access the data"
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: "Allow"
            Principal:
              CanonicalUser: !GetAtt CfOriginAccessIdentity.S3CanonicalUserId
            Resource:
              - !Sub "arn:aws:s3:::${S3Bucket}/*"
    Type: "AWS::S3::BucketPolicy"

  CfDistribution:
    Metadata:
      Comment: "CloudFront distribution digihome"
    Properties:
      DistributionConfig:
        Comment: " distribution  S3 digihome"
        DefaultCacheBehavior:
          AllowedMethods:
            - "HEAD"
            - "GET"
          CachedMethods:
            - "HEAD"
            - "GET"
          Compress: false
          DefaultTTL: 86400
          ForwardedValues:
            Cookies:
              Forward: "none"
            Headers:
              - "Origin"
            QueryString: false
          MaxTTL: 31536000
          MinTTL: 86400
          TargetOriginId: !Sub "${S3Bucket}"
          ViewerProtocolPolicy: "redirect-to-https"
        DefaultRootObject: "index.html"
        Enabled: true
        HttpVersion: "http1.1"
        IPV6Enabled: false
        Origins:
          - DomainName: !GetAtt S3Bucket.DomainName
            Id: !Sub "${S3Bucket}"
            OriginPath: ""
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CfOriginAccessIdentity}"
        PriceClass: "PriceClass_All"
    Type: "AWS::CloudFront::Distribution"

  CfOriginAccessIdentity:
    Metadata:
      Comment: "Access S3 bucket content only through CloudFront"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "Access S3 bucket content only through CloudFront"
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"

Outputs:
  S3BucketName:
    Description: "Bucket name"
    Value: !Ref S3Bucket
  CfDistributionId:
    Description: "Id for our cloudfront distribution"
    Value: !Ref CfDistribution
  CfDistributionDomainName:
    Description: "Domain name for our cloudfront distribution"
    Value: !GetAtt CfDistribution.DomainName
