export = {
  type: 'postgres',
  host: process.env.DATABASE_HOST || 'localhost',
  port: Number(process.env.DATABASE_PORT) || 5432,
  username: process.env.DATABASE_USER_NAME || 'khanhnguyen',
  password: process.env.DATABASE_PASSWORD || '12345678',
  database: process.env.DATABASE || 'digihome',
  schema: process.env.DATABASE_SCHEMA || 'public',
  synchronize: false,
  migrations: [__dirname + './../../migrations/*{.ts,.js}'],
  seeds: [__dirname + './../../seeds/*{.ts,.js}'],
  entities: [__dirname + '../../../**/**/*entity{.ts,.js}'],
  logging: true,
  migrationsRun: false,
  migrationsTableName: 'history',
  timezone: 'utc',
};
