export const COUNTRY_CODE = {
  VIETNAM: "VN",
  THAILAND: "TH",
  SG: "SG",
  CHINA: "CN",
  TAIWAN: "TW",
  JAPAN: "JP",
  KOREAN: "KR",
  HK: "HK",
  AUD: "AU",
  RUS: "RU",
};

export const LANGUAGE = {
  VIETNAM: "vi",
  THAILAND: "th",
  KOREAN: "ko",
  CHINA: "zh-CN",
  TAIWAN: "zh-TW",
  HK: "zh-TW",
  JAPAN: "ja",
  EN: "en",
  RUS: "ru",
};

export const MAP_COUNTRY_LANGUAGE = {
  [COUNTRY_CODE.VIETNAM]: LANGUAGE.VIETNAM,
  [COUNTRY_CODE.THAILAND]: LANGUAGE.THAILAND,
  [COUNTRY_CODE.KOREAN]: LANGUAGE.KOREAN,
  [COUNTRY_CODE.CHINA]: LANGUAGE.CHINA,
  [COUNTRY_CODE.HK]: LANGUAGE.HK,
  [COUNTRY_CODE.JAPAN]: LANGUAGE.JAPAN,
  [COUNTRY_CODE.AUD]: LANGUAGE.EN,
  [COUNTRY_CODE.RUS]: LANGUAGE.RUS,
};
