version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g yarn aws-cli
      - yarn install

  build:
    commands:
      - yarn build
      - aws s3 cp dist s3://evoucher-backoffice --recursive

artifacts:
  files:
    - 'dist/**/*'
